# Generated by Django 5.0.7 on 2024-07-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_journal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
