# Generated by Django 5.0.7 on 2024-07-30 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_journalreminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
