# Generated by Django 5.0.7 on 2024-07-29 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_reward_date_alter_reward_image_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='image',
            field=models.ImageField(default='rewards/fallback.png', upload_to='rewards/'),
        ),
    ]
