# Generated by Django 5.0.7 on 2024-07-29 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_reminder_description_alter_reminder_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='description',
            field=models.TextField(),
        ),
    ]
