# Generated by Django 5.0.7 on 2024-07-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_mood_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mood',
            name='user',
        ),
        migrations.AddField(
            model_name='mood',
            name='custom_mood',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mood',
            name='color',
            field=models.CharField(default='#FFFFFF', max_length=7),
        ),
    ]
