# Generated by Django 5.0.7 on 2024-07-24 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_userprofile_moodentry_dailygoal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moodentry',
            name='user',
        ),
        migrations.DeleteModel(
            name='DailyGoal',
        ),
        migrations.DeleteModel(
            name='MoodEntry',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
