# Generated by Django 5.0.7 on 2024-07-31 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0008_alter_journal_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mood',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
