# Generated by Django 5.0.7 on 2024-07-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('app', '0009_mood_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mood',
            name='color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
